In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("dataset.csv")
data.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [5]:
data.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [7]:
data.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [8]:
movies = data[['id', 'title','overview', 'genre']]

In [10]:
movies.head(10)

,id,title,overview,genre
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance"
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
5,667257,Impossible Things,"Matilde is a woman who, after the death of her...","Family,Drama"
6,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...","Animation,Family,Fantasy"
7,730154,Your Eyes Tell,"A tragic accident lead to Kaori's blindness, b...","Romance,Drama"
8,372754,Dou kyu sei – Classmates,"Rihito Sajo, an honor student with a perfect s...","Romance,Animation"
9,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,"Romance,Animation,Drama"

In [11]:
movies['tag'] = movies['overview'] + movies['genre']

C:\Users\ayush\AppData\Local\Temp\ipykernel_10320\2311850573.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tag'] = movies['overview'] + movies['genre']

In [12]:
movies.head(5)

,id,title,overview,genre,tag
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...

In [13]:
new_data = movies.drop(columns=['overview', 'genre'])

In [15]:
new_data.head(5)

,id,title,tag
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv = CountVectorizer(max_df= 10000, stop_words='english')

In [20]:
vector = cv.fit_transform(new_data['tag'].values.astype('U')).toarray()

In [23]:

from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity = cosine_similarity(vector)

In [36]:
distance = sorted(list(enumerate(similarity[2])), reverse= True, key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Blood Ties
Joker
Bomb City

In [38]:
def reccomand(movies):
    index = new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse= True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [39]:
reccomand('Iron Man')

Iron Man
Iron Man 3
Avengers: Age of Ultron
Guardians of the Galaxy Vol. 2
Charlie's Angels

In [40]:
import pickle

In [41]:
pickle.dump(new_data,open('movies_list.pkl', 'wb'))

In [45]:
pickle.dump(similarity,open('similarity.pkl', 'wb'))

In [46]:
pickle.load(open('similarity.pkl', 'rb'))

array([[1.        , 0.04402255, 0.11627907, ..., 0.06469966, 0.09539445,
        0.05763904],
       [0.04402255, 1.        , 0.06603382, ..., 0.        , 0.03009646,
        0.        ],
       [0.11627907, 0.06603382, 1.        , ..., 0.02156655, 0.0635963 ,
        0.08645856],
       ...,
       [0.06469966, 0.        , 0.02156655, ..., 1.        , 0.02948839,
        0.02672612],
       [0.09539445, 0.03009646, 0.0635963 , ..., 0.02948839, 1.        ,
        0.03940552],
       [0.05763904, 0.        , 0.08645856, ..., 0.02672612, 0.03940552,
        1.        ]])